name: Send Email

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - 'test-base-*'
  workflow_dispatch:
    inputs:
      TEST_EMAIL:
        description: 'Whether to send the email as a test'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  send-email:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
       contains(github.event.pull_request.labels.*.name, 'send-email'))

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Send email
        env:
          LISTMONK_API_KEY: ${{ secrets.LISTMONK_API_KEY }}
          LISTMONK_API_UID: ${{ secrets.LISTMONK_API_UID }}
          LISTMONK_URL: ${{ secrets.LISTMONK_URL }}
          TEST_EMAIL: ${{ github.event.inputs.TEST_EMAIL || (contains(github.event.pull_request.labels.*.name, 'test') && 'true' || 'false') }}
        run: uv run send_email.py
